### ISSUE TITLE
App Rejected Due to YouTube TOS violation

### ISSUE THREAD

**Issue by cassidyjames** [cryptowyrm/copypastegrab#1]
Thank you for submitting your app to AppCenter! Unfortunately we've had to reject the submission because downloading videos from YouTube constitutes a violation of the [YouTube terms of service](https://www.youtube.com/static?template=terms). The relevant section is 5b (emphasis added):

>…You may access Content for your information and personal use solely as intended through the provided functionality of the Service and as permitted under these Terms of Service. **You shall not download any Content unless you see a “download” or similar link displayed by YouTube** on the Service for that Content. You shall not copy, reproduce, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any Content for any other purposes without the prior written consent of YouTube or the respective licensors of the Content…

The [AppCenter legal requirements](https://github.com/elementary/houston/wiki/Before-You-Publish#legal-requirements) state (emphasis added):

>**Your app must comply with** all applicable laws as well as **the terms of any services your app utilizes.**

Lastly, to clarify: it's not the latent ability to download YouTube videos that is problematic to me, it is the encouraging of breaking the TOS that is. If CopyPasteGrab was designed and advertised to download video from sources that allow it, then it could be a different story.

Thank you very much for your time and effort. We hope that this doesn't deter you from developing other apps for elementary OS. If your app becomes compliant, feel free to resubmit it!

**Comment by cryptowyrm** [comment]
Hi @cassidyjames, thanks for your message!

The app itself doesn't download videos, it's just a GUI for youtube-dl (it just sends shell commands to the youtube-dl command line application) which is already included in the Ubuntu repository elementaryOS uses and downloads videos from hundreds of websites, not just YouTube.

Am I right to assume that it's okay if I remove the YouTube URLs used in the screenshots? I can just use mock data there, make up the URLs for the screenshots. Or do I also have to remove the reference to youtube-dl in the AppCenter description because the name YouTube is in the name of the Ubuntu package? That's the only places I can think of where YouTube is mentioned.

And don't worry, it's unfortunate since I will now have to wait even longer for my app to appear in the AppCenter, but it doesn't deter me, I will resubmit the app quickly with the changes I need to make and plan to write a few more elementary OS apps over time once I got this one published.

By the way, I wrote about my elementaryOS development experience here: https://steemit.com/technology/@crypticwyrm/developing-an-app-for-elem ntary-os-5-juno-with-vala-my-first-experience-and-helpful-resources

With 349 Upvotes it was by far my most popular post since I started blogging a year and a half ago, thought you might be interested to hear that there is apparently a ton of new interest in developing elementary OS apps :)

**Comment by cryptowyrm** [comment]
I changed the screenshot and edited all the metadata files to remove all mentions of youtube-dl and YouTube URLs.

I also added a disclaimer to the AppCenter description: "Note: Not all video websites allow downloading videos, so make sure you only download from websites that explicitly allow downloading videos in their Terms of Service."

I believe that should now make the app fully compliant, so I will now resubmit it to the AppCenter.
